# Generated by Django 2.2.7 on 2019-11-25 10:18

from django.db import migrations, models
import django.db.models.deletion
import simpsonapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('about', models.CharField(blank=True, max_length=1500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=simpsonapp.models.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True)),
                ('about', models.TextField(max_length=1500, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='simpsonapp.Client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simpsonapp.Contact'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=simpsonapp.models.get_image_path)),
                ('image_2', models.ImageField(blank=True, upload_to=simpsonapp.models.get_image_path)),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=25)),
                ('birthday', models.DateField(null=True)),
                ('likes', models.TextField(max_length=600, null=True)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simpsonapp.Contact')),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='simpsonapp.Project')),
            ],
        ),
    ]
