# Generated by Django 2.2.7 on 2019-11-10 18:11

from django.db import migrations, models
import django.db.models.deletion
import simpsonapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('about', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True)),
                ('about', models.TextField(max_length=1500, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='simpsonapp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=simpsonapp.models.get_image_path)),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=25)),
                ('birthday', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('info', models.TextField(max_length=600, null=True)),
                ('likes', models.TextField(max_length=600, null=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simpsonapp.Projects')),
            ],
        ),
    ]
