# Generated by Django 2.2.7 on 2019-11-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpsonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='contact_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='simpsonapp.Contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='simpsonapp.Contact'),
        ),
    ]
