# Generated by Django 2.2.7 on 2019-11-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpsonapp', '0003_auto_20191125_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='image',
            new_name='portrait_image',
        ),
    ]
